spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: main
          uri: lb://JUJEOL-JUJEOL
          predicates:
            - Path=/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://3.34.90.107/eureka
